language: java
sudo: required
dist: xenial
jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2/repository

script:
  - ./mvnw test -e

after_success:
  - ./mvnw clean test jacoco:report coveralls:report