language: java
sudo: true
dist: trusty
jdk: oraclejdk11
addons:
  apt:
    packages:
      - oracle-java11-installer
before_install:
  - chmod +x mvnw

env:
  global:
    - TOKEN=TOKEN

cache:
  directories:
    - $HOME/.m2

script:
  - ./mvnw test -e

after_success:
  - ./mvnw clean test jacoco:report coveralls:report